
#ifndef _SYMBOLS
#define _SYMBOLS

enum symbols
{
	S_Unknown = 2000,
	S_Global,
	S_Name,
	S_Variable,

	S_ARRAY_LENGTH,
	S_ARRAY,
	S_INPUTSTREAM_CLOSE,
	S_INPUTSTREAM_READ,
	S_INPUTSTREAM,
	S_PRINTSTREAM_PRINT,
	S_PRINTSTREAM_PRINTLN,
	S_PRINTSTREAM,
	S_STRING_CHARAT,
	S_STRING_COMPARETO,
	S_STRING_EQUALS,
	S_STRING_JOIN,
	S_STRING_LENGTH,
	S_STRING_SUBSTRING,
	S_STRING_VALUEOF,
	S_STRING,
	S_SYSTEM_ERR_PRINT,
	S_SYSTEM_ERR_PRINTLN,
	S_SYSTEM_ERR,
	S_SYSTEM_EXIT,
	S_SYSTEM_OUT_PRINT,
	S_SYSTEM_OUT_PRINTLN,
	S_SYSTEM_OUT,
	S_SYSTEM,
};
#endif
